// Generated by gencpp from file server/show.msg
// DO NOT EDIT!


#ifndef SERVER_MESSAGE_SHOW_H
#define SERVER_MESSAGE_SHOW_H

#include <ros/service_traits.h>


#include <server/showRequest.h>
#include <server/showResponse.h>


namespace server
{

struct show
{

typedef showRequest Request;
typedef showResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct show
} // namespace server


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::server::show > {
  static const char* value()
  {
    return "cfe71d70b666fd27790ae59c4609bc1d";
  }

  static const char* value(const ::server::show&) { return value(); }
};

template<>
struct DataType< ::server::show > {
  static const char* value()
  {
    return "server/show";
  }

  static const char* value(const ::server::show&) { return value(); }
};


// service_traits::MD5Sum< ::server::showRequest> should match
// service_traits::MD5Sum< ::server::show >
template<>
struct MD5Sum< ::server::showRequest>
{
  static const char* value()
  {
    return MD5Sum< ::server::show >::value();
  }
  static const char* value(const ::server::showRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::server::showRequest> should match
// service_traits::DataType< ::server::show >
template<>
struct DataType< ::server::showRequest>
{
  static const char* value()
  {
    return DataType< ::server::show >::value();
  }
  static const char* value(const ::server::showRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::server::showResponse> should match
// service_traits::MD5Sum< ::server::show >
template<>
struct MD5Sum< ::server::showResponse>
{
  static const char* value()
  {
    return MD5Sum< ::server::show >::value();
  }
  static const char* value(const ::server::showResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::server::showResponse> should match
// service_traits::DataType< ::server::show >
template<>
struct DataType< ::server::showResponse>
{
  static const char* value()
  {
    return DataType< ::server::show >::value();
  }
  static const char* value(const ::server::showResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SERVER_MESSAGE_SHOW_H
