// Generated by gencpp from file client/loginRequest.msg
// DO NOT EDIT!


#ifndef CLIENT_MESSAGE_LOGINREQUEST_H
#define CLIENT_MESSAGE_LOGINREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace client
{
template <class ContainerAllocator>
struct loginRequest_
{
  typedef loginRequest_<ContainerAllocator> Type;

  loginRequest_()
    : req_code(0)
    , node_name()  {
    }
  loginRequest_(const ContainerAllocator& _alloc)
    : req_code(0)
    , node_name(_alloc)  {
  (void)_alloc;
    }



   typedef uint16_t _req_code_type;
  _req_code_type req_code;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _node_name_type;
  _node_name_type node_name;





  typedef boost::shared_ptr< ::client::loginRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::client::loginRequest_<ContainerAllocator> const> ConstPtr;

}; // struct loginRequest_

typedef ::client::loginRequest_<std::allocator<void> > loginRequest;

typedef boost::shared_ptr< ::client::loginRequest > loginRequestPtr;
typedef boost::shared_ptr< ::client::loginRequest const> loginRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::client::loginRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::client::loginRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::client::loginRequest_<ContainerAllocator1> & lhs, const ::client::loginRequest_<ContainerAllocator2> & rhs)
{
  return lhs.req_code == rhs.req_code &&
    lhs.node_name == rhs.node_name;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::client::loginRequest_<ContainerAllocator1> & lhs, const ::client::loginRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace client

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::client::loginRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::client::loginRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::client::loginRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::client::loginRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::client::loginRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::client::loginRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::client::loginRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "493479b65998b0b2b28fbe4e963ea7e6";
  }

  static const char* value(const ::client::loginRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x493479b65998b0b2ULL;
  static const uint64_t static_value2 = 0xb28fbe4e963ea7e6ULL;
};

template<class ContainerAllocator>
struct DataType< ::client::loginRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "client/loginRequest";
  }

  static const char* value(const ::client::loginRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::client::loginRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint16 req_code\n"
"string node_name\n"
;
  }

  static const char* value(const ::client::loginRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::client::loginRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.req_code);
      stream.next(m.node_name);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct loginRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::client::loginRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::client::loginRequest_<ContainerAllocator>& v)
  {
    s << indent << "req_code: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.req_code);
    s << indent << "node_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.node_name);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CLIENT_MESSAGE_LOGINREQUEST_H
