// Generated by gencpp from file client/login.msg
// DO NOT EDIT!


#ifndef CLIENT_MESSAGE_LOGIN_H
#define CLIENT_MESSAGE_LOGIN_H

#include <ros/service_traits.h>


#include <client/loginRequest.h>
#include <client/loginResponse.h>


namespace client
{

struct login
{

typedef loginRequest Request;
typedef loginResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct login
} // namespace client


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::client::login > {
  static const char* value()
  {
    return "ec021ca287a263e3d68ad93e1193a7d9";
  }

  static const char* value(const ::client::login&) { return value(); }
};

template<>
struct DataType< ::client::login > {
  static const char* value()
  {
    return "client/login";
  }

  static const char* value(const ::client::login&) { return value(); }
};


// service_traits::MD5Sum< ::client::loginRequest> should match
// service_traits::MD5Sum< ::client::login >
template<>
struct MD5Sum< ::client::loginRequest>
{
  static const char* value()
  {
    return MD5Sum< ::client::login >::value();
  }
  static const char* value(const ::client::loginRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::client::loginRequest> should match
// service_traits::DataType< ::client::login >
template<>
struct DataType< ::client::loginRequest>
{
  static const char* value()
  {
    return DataType< ::client::login >::value();
  }
  static const char* value(const ::client::loginRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::client::loginResponse> should match
// service_traits::MD5Sum< ::client::login >
template<>
struct MD5Sum< ::client::loginResponse>
{
  static const char* value()
  {
    return MD5Sum< ::client::login >::value();
  }
  static const char* value(const ::client::loginResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::client::loginResponse> should match
// service_traits::DataType< ::client::login >
template<>
struct DataType< ::client::loginResponse>
{
  static const char* value()
  {
    return DataType< ::client::login >::value();
  }
  static const char* value(const ::client::loginResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CLIENT_MESSAGE_LOGIN_H
