// Generated by gencpp from file client/loginResponse.msg
// DO NOT EDIT!


#ifndef CLIENT_MESSAGE_LOGINRESPONSE_H
#define CLIENT_MESSAGE_LOGINRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace client
{
template <class ContainerAllocator>
struct loginResponse_
{
  typedef loginResponse_<ContainerAllocator> Type;

  loginResponse_()
    : ack_code(0)  {
    }
  loginResponse_(const ContainerAllocator& _alloc)
    : ack_code(0)  {
  (void)_alloc;
    }



   typedef uint16_t _ack_code_type;
  _ack_code_type ack_code;





  typedef boost::shared_ptr< ::client::loginResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::client::loginResponse_<ContainerAllocator> const> ConstPtr;

}; // struct loginResponse_

typedef ::client::loginResponse_<std::allocator<void> > loginResponse;

typedef boost::shared_ptr< ::client::loginResponse > loginResponsePtr;
typedef boost::shared_ptr< ::client::loginResponse const> loginResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::client::loginResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::client::loginResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::client::loginResponse_<ContainerAllocator1> & lhs, const ::client::loginResponse_<ContainerAllocator2> & rhs)
{
  return lhs.ack_code == rhs.ack_code;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::client::loginResponse_<ContainerAllocator1> & lhs, const ::client::loginResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace client

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::client::loginResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::client::loginResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::client::loginResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::client::loginResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::client::loginResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::client::loginResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::client::loginResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7f47bb5ecdb3f7ca57312d7a1a86406b";
  }

  static const char* value(const ::client::loginResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7f47bb5ecdb3f7caULL;
  static const uint64_t static_value2 = 0x57312d7a1a86406bULL;
};

template<class ContainerAllocator>
struct DataType< ::client::loginResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "client/loginResponse";
  }

  static const char* value(const ::client::loginResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::client::loginResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint16 ack_code\n"
;
  }

  static const char* value(const ::client::loginResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::client::loginResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.ack_code);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct loginResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::client::loginResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::client::loginResponse_<ContainerAllocator>& v)
  {
    s << indent << "ack_code: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.ack_code);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CLIENT_MESSAGE_LOGINRESPONSE_H
