// Generated by gencpp from file client/show.msg
// DO NOT EDIT!


#ifndef CLIENT_MESSAGE_SHOW_H
#define CLIENT_MESSAGE_SHOW_H

#include <ros/service_traits.h>


#include <client/showRequest.h>
#include <client/showResponse.h>


namespace client
{

struct show
{

typedef showRequest Request;
typedef showResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct show
} // namespace client


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::client::show > {
  static const char* value()
  {
    return "cfe71d70b666fd27790ae59c4609bc1d";
  }

  static const char* value(const ::client::show&) { return value(); }
};

template<>
struct DataType< ::client::show > {
  static const char* value()
  {
    return "client/show";
  }

  static const char* value(const ::client::show&) { return value(); }
};


// service_traits::MD5Sum< ::client::showRequest> should match
// service_traits::MD5Sum< ::client::show >
template<>
struct MD5Sum< ::client::showRequest>
{
  static const char* value()
  {
    return MD5Sum< ::client::show >::value();
  }
  static const char* value(const ::client::showRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::client::showRequest> should match
// service_traits::DataType< ::client::show >
template<>
struct DataType< ::client::showRequest>
{
  static const char* value()
  {
    return DataType< ::client::show >::value();
  }
  static const char* value(const ::client::showRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::client::showResponse> should match
// service_traits::MD5Sum< ::client::show >
template<>
struct MD5Sum< ::client::showResponse>
{
  static const char* value()
  {
    return MD5Sum< ::client::show >::value();
  }
  static const char* value(const ::client::showResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::client::showResponse> should match
// service_traits::DataType< ::client::show >
template<>
struct DataType< ::client::showResponse>
{
  static const char* value()
  {
    return DataType< ::client::show >::value();
  }
  static const char* value(const ::client::showResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CLIENT_MESSAGE_SHOW_H
