// Generated by gencpp from file client/showResponse.msg
// DO NOT EDIT!


#ifndef CLIENT_MESSAGE_SHOWRESPONSE_H
#define CLIENT_MESSAGE_SHOWRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace client
{
template <class ContainerAllocator>
struct showResponse_
{
  typedef showResponse_<ContainerAllocator> Type;

  showResponse_()
    : response(0)  {
    }
  showResponse_(const ContainerAllocator& _alloc)
    : response(0)  {
  (void)_alloc;
    }



   typedef uint8_t _response_type;
  _response_type response;





  typedef boost::shared_ptr< ::client::showResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::client::showResponse_<ContainerAllocator> const> ConstPtr;

}; // struct showResponse_

typedef ::client::showResponse_<std::allocator<void> > showResponse;

typedef boost::shared_ptr< ::client::showResponse > showResponsePtr;
typedef boost::shared_ptr< ::client::showResponse const> showResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::client::showResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::client::showResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::client::showResponse_<ContainerAllocator1> & lhs, const ::client::showResponse_<ContainerAllocator2> & rhs)
{
  return lhs.response == rhs.response;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::client::showResponse_<ContainerAllocator1> & lhs, const ::client::showResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace client

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::client::showResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::client::showResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::client::showResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::client::showResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::client::showResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::client::showResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::client::showResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "59064532f110d857c53f36f4ab7ad30a";
  }

  static const char* value(const ::client::showResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x59064532f110d857ULL;
  static const uint64_t static_value2 = 0xc53f36f4ab7ad30aULL;
};

template<class ContainerAllocator>
struct DataType< ::client::showResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "client/showResponse";
  }

  static const char* value(const ::client::showResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::client::showResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 response\n"
"\n"
;
  }

  static const char* value(const ::client::showResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::client::showResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.response);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct showResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::client::showResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::client::showResponse_<ContainerAllocator>& v)
  {
    s << indent << "response: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.response);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CLIENT_MESSAGE_SHOWRESPONSE_H
