// Generated by gencpp from file client/time.msg
// DO NOT EDIT!


#ifndef CLIENT_MESSAGE_TIME_H
#define CLIENT_MESSAGE_TIME_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace client
{
template <class ContainerAllocator>
struct time_
{
  typedef time_<ContainerAllocator> Type;

  time_()
    : sec()
    , name()  {
    }
  time_(const ContainerAllocator& _alloc)
    : sec(_alloc)
    , name(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _sec_type;
  _sec_type sec;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _name_type;
  _name_type name;





  typedef boost::shared_ptr< ::client::time_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::client::time_<ContainerAllocator> const> ConstPtr;

}; // struct time_

typedef ::client::time_<std::allocator<void> > time;

typedef boost::shared_ptr< ::client::time > timePtr;
typedef boost::shared_ptr< ::client::time const> timeConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::client::time_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::client::time_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::client::time_<ContainerAllocator1> & lhs, const ::client::time_<ContainerAllocator2> & rhs)
{
  return lhs.sec == rhs.sec &&
    lhs.name == rhs.name;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::client::time_<ContainerAllocator1> & lhs, const ::client::time_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace client

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::client::time_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::client::time_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::client::time_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::client::time_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::client::time_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::client::time_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::client::time_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9fbfca278f613909c27792d3987b7cbf";
  }

  static const char* value(const ::client::time_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9fbfca278f613909ULL;
  static const uint64_t static_value2 = 0xc27792d3987b7cbfULL;
};

template<class ContainerAllocator>
struct DataType< ::client::time_<ContainerAllocator> >
{
  static const char* value()
  {
    return "client/time";
  }

  static const char* value(const ::client::time_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::client::time_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string sec\n"
"string name\n"
;
  }

  static const char* value(const ::client::time_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::client::time_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.sec);
      stream.next(m.name);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct time_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::client::time_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::client::time_<ContainerAllocator>& v)
  {
    s << indent << "sec: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.sec);
    s << indent << "name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.name);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CLIENT_MESSAGE_TIME_H
